Add skins to automated upgrading

diff --git a/uesp-getmwext b/uesp-getmwext
--- a/uesp-getmwext
+++ b/uesp-getmwext
@@ -4,10 +4,36 @@
 
 #BASESITE="https://github.com/wikimedia/mediawiki-extensions-"
 #BASESITE="https://codeload.github.com/eckserah/mediawiki-extensions-"
+function get_file(){
+	local url="$1"
+	local outputFile="$2"
+	local success=0
+	wget -q "$url" -O "$outputFile"
+	if [ $? -ne 0 ]; then
+		echo "ERROR: Failed to download from $URL!"
+		success=3
+	fi
+	return "$success"
+}
+
+function get_gerrit() {
+	local basesite="https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/$BASETYPE/$EXTNAME"
+	local COMMITURL="$basesite/+/refs/tags/REL$EXTVERSION"
+	ARCHCOMMIT=$(curl $COMMITURL | grep -oP '(?<=commit</th><td>).*(?=</td><td><span>\[<a href)')
+	if [ -z "$ARCHCOMMIT" ]; then
+		echo "ERROR: Unable to get commit from gerrit url ($COMMITURL) for tag REL$EXTVERSION"
+		return 6
+	fi
+	URL="$basesite/+archive/$ARCHCOMMIT.tar.gz"
+	OUTPUTFILE="$EXTNAME.tar.gz"
+	get_file "$URL" "$OUTPUTFILE"
+	return $?
+}
+
 EXTNAME="$1"
 EXTVERSION="$2"
-EXTSECONDARY="$3"
-OLDPATH="mediawiki-extensions-$EXTNAME-REL$EXTVERSION"
+EXTSKINS="$3"
+BASETYPE="skins"
 
 if [ -z "$EXTNAME" ]; then
 	echo "ERROR: Missing required extension name..."
@@ -19,35 +45,40 @@ if [ -z "$EXTVERSION" ]; then
 	exit -2
 fi
 
-if [ -z "$EXTSECONDARY" ]; then
-	BASESITE="https://codeload.github.com/wikimedia/mediawiki-extensions-"
-	URL="$BASESITE$EXTNAME/zip/refs/heads/REL$EXTVERSION"
-else
-	BASESITE="https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/$EXTNAME"
-	COMMITURL="$BASESITE/+/refs/tags/REL$EXTVERSION"
-	ARCHCOMMIT=$(curl $COMMITURL | grep -oP '(?<=commit</th><td>).*(?=</td><td><span>\[<a href)')
-	if [ -z "$ARCHCOMMIT" ]; then
-		echo "ERROR: Unable to get commit from gerrit url ($COMMITURL) for tag REL$EXTVERSION"
-		exit -6
-	fi
-	URL="$BASESITE/+archive/$ARCHCOMMIT.tar.gz"
+if [ -z "$EXTSKINS" ]; then
+	BASETYPE="extensions"
 fi
+
+OLDPATH="mediawiki-$BASETYPE-$EXTNAME-REL$EXTVERSION"
+
+BASESITE="https://codeload.github.com/wikimedia/mediawiki-$BASETYPE-"
+URL="$BASESITE$EXTNAME/zip/refs/heads/REL$EXTVERSION"
 
 OUTPUTFILE="$EXTNAME.zip"
 
-echo "Attempting to download MediaWiki extension $EXTNAME v$EXTVERSION..."
+echo "Attempting to download MediaWiki $BASETYPE $EXTNAME v$EXTVERSION..."
 
-wget -q "$URL" -O "$OUTPUTFILE"
+get_file "$URL" "$OUTPUTFILE"
 
 if [ $? -ne 0 ]; then
-	echo "ERROR: Failed to download from $URL!"
-	exit -3
+	get_gerrit
+	if [ $? -ne 0 ]; then
+		exit $?
+	fi
 fi
 
-unzip -o -q "$OUTPUTFILE"
+UNZIPTYPE="unzip"
+
+if [[ "${URL: -3}" != ".gz" ]]; then
+	unzip -o -q "$OUTPUTFILE"
+else
+	mkdir -p "./mediawiki-$BASETYPE-$EXTNAME-REL$EXTVERSION"
+	tar -xzf "$OUTPUTFILE" -C "./mediawiki-$BASETYPE-$EXTNAME-REL$EXTVERSION"
+	UNZIPTYPE="untar"
+fi
 
 if [ $? -ne 0 ]; then
-	echo "ERROR: Failed to unzip $OUTPUTFILE!"
+	echo "ERROR: Failed to $UNZIPTYPE $OUTPUTFILE!"
 	exit -4
 fi
 
@@ -56,8 +87,8 @@ rm -rf "$NEWPATH"
 mv -f "$OLDPATH" "$NEWPATH"
 
 if [ $? -ne 0 ]; then
-	echo "ERROR: Failed to move outout directory $OLDPATH!"
+	echo "ERROR: Failed to move output directory $OLDPATH!"
 	exit -5
 fi
 
-echo "Successfully uncompressed MediaWiki extension to $NEWPATH..."
+echo "Successfully uncompressed MediaWiki $BASETYPE to $NEWPATH..."
